language: python
python:
  - "2.7"
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install .
#  command to run tests 
script: "python setup.py test"
